from __future__ import annotations

from typing import Protocol


class Buffer(Protocol):
    async def publish(self, events: list[dict]) -> None: ...
    async def get_batch(self, max_items: int, timeout_s: float) -> list[dict]: ...
    async def commit(self) -> None: ...
    async def close(self) -> None: ...
