from __future__ import annotations

from typing import Protocol

DEFAULT_TENANT = "default"


class Store(Protocol):
    async def index(self, events: list[dict]) -> int: ...
    async def search(self, tenant: str = DEFAULT_TENANT, q: str = "", level: str = "", service: str = "", limit: int = 100) -> list[dict]: ...
    async def count(self, tenant: str = DEFAULT_TENANT) -> int: ...
    async def stats(self, tenant: str = DEFAULT_TENANT) -> dict: ...
    async def record_alert(self, alert: dict) -> None: ...
    async def recent_alerts(self, tenant: str = DEFAULT_TENANT, limit: int = 20) -> list[dict]: ...
    async def apply_retention(self) -> int: ...
    async def close(self) -> None: ...
